environment_file: "$(find smarc_stonefish_worlds)/data/algae/algae_env.scn"
latitude: "58.250833"
longitude: "11.450283"
anchoring_buoy: "$(find smarc_stonefish_worlds)/data/algae/components/anchoring_buoy.obj"
anchoring_buoy_rope: "$(find smarc_stonefish_worlds)/data/algae/components/anchoring_chain.obj"
a0_buoy: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy.obj"
a0_buoy_rope: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy_rope.obj"
rope: "$(find smarc_stonefish_worlds)/data/algae/components/rope.obj"
algae_obj_dir: "$(find smarc_stonefish_worlds)/data/algae/algae_cube"
algae_texture_dir: "$(find smarc_stonefish_worlds)/data/algae/textures"
