environment_file: "$(find smarc_stonefish_worlds)/data/algae/algae_env_small.scn"
latitude: "58.250833"
longitude: "11.450283"
anchoring_buoy_rope: "$(find smarc_stonefish_worlds)/data/algae/components/anchoring_chain.obj"
a0_buoy: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy.obj"
rope: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy_ropes_small_farm.obj"
algae_texture_dir: "$(find smarc_stonefish_worlds)/data/algae/textures"
algae_row1: "$(find smarc_stonefish_worlds)/data/algae/components/algae_row1_small_farm.obj"
algae_row2: "$(find smarc_stonefish_worlds)/data/algae/components/algae_row2_small_farm.obj"
