robot_file: "$(find sam_stonefish_sim)/data/sam_auv/sam_auv.xml"
environment_file: "$(find sam_stonefish_sim)/data/biograd_world/biograd_env.scn" 
robot_name: "sam"
robot1_pos: "0.0 0.0 0.0"
robot2_pos: "0.0 2.0 0.0"
robot3_pos: "0.0 4.0 0.0"
robot4_pos: "0.0 6.0 0.0"
latitude: "43.93183"
longitude: "15.44264"
simulate_dr: true
