robot_file: "$(find sam_stonefish_sim)/data/sam_auv/sam_auv.xml"
environment_file: "$(find algae_world)/data/algae/algae_env.scn"
robot_name: "sam"
robot_pos: "0.0 0.0 0.0"
latitude: "43.93183"
longitude: "15.44264"
simulate_dr: "true"
anchoring_buoy: "$(find algae_world)/data/algae/components/anchoring_buoy.obj"
anchoring_buoy_rope: "$(find algae_world)/data/algae/components/anchoring_chain.obj"
a0_buoy: "$(find algae_world)/data/algae/components/a0_buoy.obj"
a0_buoy_rope: "$(find algae_world)/data/algae/components/a0_buoy_rope.obj"
rope: "$(find algae_world)/data/algae/components/rope.obj"
algae_obj_dir: "$(find algae_world)/data/algae/algae_cube"
algae_texture_dir: "$(find algae_world)/data/algae/textures"
