
robot_file: "$(find sam_stonefish_sim)/data/sam_auv/sam_auv_no_payload_sensors.xml"
environment_file: "$(find sam_stonefish_sim)/data/biograd_world/biograd_env.scn" 
robot_name: "sam"
robot_pos: "0.0 0.0 0.0"
latitude: "43.93183"
longitude: "15.44264"
simulate_dr: "true"
