robot_file: "$(find lolo_stonefish_sim)/data/lolo_auv/lolo_auv.xml"
environment_file: "$(find smarc_stonefish_worlds)/data/biograd_world/biograd_env.scn" 
robot_name: "lolo"
robot_pos: "0.0 0.0 0.0"
latitude: "43.93183"
longitude: "15.44264"
simulate_dr: "true"
