on: [push]

jobs:
  test-release-job:
      strategy:
        matrix:
          include:
            - distro: melodic
              ubuntu: bionic
              bloom: python-bloom
            - distro: noetic
              ubuntu: focal
              bloom: python3-bloom
      runs-on: ubuntu-latest
      name: Test building a ROS debian release
      steps:
      - uses: actions/checkout@v2
        with:
          path: '.'
      - name: Run the release build
        uses: smarc-project/test-ros-release-action@v1.0.3
        with:
          ubuntu: ${{ matrix.ubuntu }}
          distro: ${{ matrix.distro }}
